import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { DomainConfig } from '@memberjunction/loom-contracts';

export interface DateFixOptions {
  outputDir: string;
  domain: DomainConfig;
  dateColumnMap?: Record<string, string>; // entity -> logical date column name (e.g. 'JoinedAt', 'OrderDate')
}

/**
 * Emits a simple one-time SQL script to align MemberJunction system columns
 * (__mj_CreatedAt, __mj_UpdatedAt) with the simulated 5-year history dates.
 */
export async function emitBaselineDateFixScript(options: DateFixOptions): Promise<string> {
  await fs.mkdir(options.outputDir, { recursive: true });

  const filePath = path.join(options.outputDir, 'R__Align_Simulated_Baseline_Dates.sql');
  const lines: string[] = [
    `-- =============================================================================`,
    `-- Repeatable / One-Time Script: Align Simulated Baseline History Dates`,
    `-- Generated by Loom Simulation Engine (MemberJunction)`,
    `-- =============================================================================`,
    ``,
    `BEGIN TRANSACTION;`,
    ``,
  ];

  for (const [entityName, entityCfg] of Object.entries(options.domain.entities)) {
    const table = `[${entityCfg.schema}].[${entityCfg.targetTable}]`;
    const logicalDateCol = options.dateColumnMap?.[entityName] ?? 'CreatedAt';

    lines.push(`-- Align dates for ${entityName}`);
    lines.push(`IF COL_LENGTH('${entityCfg.schema}.${entityCfg.targetTable}', '__mj_CreatedAt') IS NOT NULL`);
    lines.push(`BEGIN`);
    lines.push(`    UPDATE ${table}`);
    lines.push(`    SET [__mj_CreatedAt] = COALESCE([${logicalDateCol}], [__mj_CreatedAt]),`);
    lines.push(`        [__mj_UpdatedAt] = COALESCE([${logicalDateCol}], [__mj_UpdatedAt])`);
    lines.push(`    WHERE [__mj_CreatedAt] > GETUTCDATE() OR [__mj_CreatedAt] IS NULL;`);
    lines.push(`END;`);
    lines.push(``);
  }

  lines.push(`COMMIT TRANSACTION;`);
  lines.push(``);

  await fs.writeFile(filePath, lines.join('\n'), 'utf8');
  return filePath;
}
