import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { DomainConfig } from '@memberjunction/loom-contracts';

export interface DateFixOptions {
  outputDir: string;
  domain: DomainConfig;
  dateColumnMap?: Record<string, string>; // entity -> logical date column name
  dialect?: 'sqlserver' | 'postgres';
}

/**
 * Emits an idempotent, safe SQL script to align MemberJunction system columns
 * (__mj_CreatedAt, __mj_UpdatedAt) with simulated baseline history dates.
 * Only executes updates on tables where both the system column and the target date column exist.
 */
export async function emitBaselineDateFixScript(options: DateFixOptions): Promise<string> {
  await fs.mkdir(options.outputDir, { recursive: true });

  const isPostgres = options.dialect === 'postgres';
  const filePath = path.join(options.outputDir, 'R__Align_Simulated_Baseline_Dates.sql');
  const lines: string[] = [
    `-- =============================================================================`,
    `-- Repeatable Script: Align Simulated Baseline History Dates`,
    `-- Generated by Loom Simulation Engine (MemberJunction)`,
    `-- Target Dialect: ${options.dialect ?? 'sqlserver'}`,
    `-- =============================================================================`,
    ``,
    isPostgres ? `BEGIN;` : `BEGIN TRANSACTION;`,
    ``,
  ];

  for (const [entityName, entityCfg] of Object.entries(options.domain.entities)) {
    const schema = entityCfg.schema ?? 'dbo';
    const table = entityCfg.targetTable ?? entityName;
    const logicalDateCol = options.dateColumnMap?.[entityName] ?? 'CreatedAt';

    lines.push(`-- Align dates for ${entityName}`);
    if (isPostgres) {
      lines.push(`DO $$`);
      lines.push(`BEGIN`);
      lines.push(`    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = '${schema}' AND table_name = '${table}' AND column_name = '__mj_CreatedAt') AND`);
      lines.push(`       EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = '${schema}' AND table_name = '${table}' AND column_name = '${logicalDateCol}') THEN`);
      lines.push(`        EXECUTE 'UPDATE "${schema}"."${table}" SET "__mj_CreatedAt" = COALESCE("${logicalDateCol}", "__mj_CreatedAt"), "__mj_UpdatedAt" = COALESCE("${logicalDateCol}", "__mj_UpdatedAt")';`);
      lines.push(`    END IF;`);
      lines.push(`END $$;`);
    } else {
      lines.push(`IF COL_LENGTH('${schema}.${table}', '__mj_CreatedAt') IS NOT NULL AND COL_LENGTH('${schema}.${table}', '${logicalDateCol}') IS NOT NULL`);
      lines.push(`BEGIN`);
      lines.push(`    EXEC('UPDATE [${schema}].[${table}] SET [__mj_CreatedAt] = COALESCE([${logicalDateCol}], [__mj_CreatedAt]), [__mj_UpdatedAt] = COALESCE([${logicalDateCol}], [__mj_UpdatedAt])');`);
      lines.push(`END;`);
    }
    lines.push(``);
  }

  lines.push(isPostgres ? `COMMIT;` : `COMMIT TRANSACTION;`);
  lines.push(``);

  await fs.writeFile(filePath, lines.join('\n'), 'utf8');
  return filePath;
}
