import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { DomainConfig } from '@memberjunction/loom-contracts';

export interface SkywayMigrationOptions {
  outputDir: string;
  version: string;
  description: string;
  domain: DomainConfig;
  data: Record<string, readonly Record<string, unknown>[]>;
  dialect?: 'sqlserver' | 'postgres';
  useSpCreate?: boolean;
}

/**
 * Emits additive Skyway migrations with dual-dialect support (SQL Server & PostgreSQL).
 * Validates all emitted columns against domain entity field declarations.
 * Properly escapes JSON objects and strings, avoiding [object Object] leaks.
 */
export async function emitSkywayMigration(options: SkywayMigrationOptions): Promise<string> {
  await fs.mkdir(options.outputDir, { recursive: true });

  const dialect = options.dialect ?? 'sqlserver';
  const isPostgres = dialect === 'postgres';
  const safeDesc = options.description.replace(/[^a-zA-Z0-9_]/g, '_');
  const fileName = `V${options.version}__${safeDesc}.sql`;
  const filePath = path.join(options.outputDir, fileName);

  const lines: string[] = [
    `-- =============================================================================`,
    `-- Migration: ${fileName}`,
    `-- Generated by Loom Simulation Engine (MemberJunction)`,
    `-- Target Dialect: ${dialect}`,
    `-- =============================================================================`,
    ``,
    isPostgres ? `BEGIN;` : `BEGIN TRANSACTION;`,
    ``,
  ];

  for (const [entityName, records] of Object.entries(options.data)) {
    if (records.length === 0) continue;
    const entityCfg = options.domain.entities[entityName];
    if (!entityCfg) {
      throw new Error(`emitSkywayMigration: entity '${entityName}' is not defined in domain configuration`);
    }

    const schemaName = entityCfg.schema ?? 'dbo';
    const tableName = entityCfg.targetTable ?? entityName;
    const declaredFields = new Set(Object.keys(entityCfg.fields));

    // Allow primary key and standard audit fields if present
    declaredFields.add('ID');
    declaredFields.add('id');
    declaredFields.add('CreatedAt');
    declaredFields.add('UpdatedAt');

    const fullTableName = isPostgres
      ? `"${schemaName}"."${tableName}"`
      : `[${schemaName}].[${tableName}]`;

    lines.push(`-- Entity: ${entityName} (${records.length} records)`);

    for (const record of records) {
      const cols = Object.keys(record);

      // Validate that all columns exist in domain configuration
      for (const col of cols) {
        if (!declaredFields.has(col)) {
          throw new Error(
            `emitSkywayMigration: undeclared column '${col}' in entity '${entityName}'. Emitted columns must be declared in domain.json.`
          );
        }
      }

      const colList = isPostgres
        ? cols.map((c) => `"${c}"`).join(', ')
        : cols.map((c) => `[${c}]`).join(', ');

      const valList = cols
        .map((col) => formatSqlValue(record[col], isPostgres))
        .join(', ');

      if (options.useSpCreate) {
        if (isPostgres) {
          // PostgreSQL procedure call: CALL "schema"."spCreate"(...)
          lines.push(`CALL "${schemaName}"."spCreate${tableName}"(${valList});`);
        } else {
          // SQL Server stored procedure call: EXEC [schema].[spCreate...] @col = val
          const paramList = cols
            .map((c) => `@${c} = ${formatSqlValue(record[c], isPostgres)}`)
            .join(', ');
          lines.push(`EXEC [${schemaName}].[spCreate${tableName}] ${paramList};`);
        }
      } else {
        // Direct transactional SQL insert
        lines.push(`INSERT INTO ${fullTableName} (${colList}) VALUES (${valList});`);
      }
    }
    lines.push(``);
  }

  lines.push(isPostgres ? `COMMIT;` : `COMMIT TRANSACTION;`);
  lines.push(``);

  await fs.writeFile(filePath, lines.join('\n'), 'utf8');
  return filePath;
}

function formatSqlValue(val: unknown, isPostgres: boolean): string {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return String(val);
  if (typeof val === 'boolean') return isPostgres ? (val ? 'TRUE' : 'FALSE') : val ? '1' : '0';

  if (typeof val === 'object') {
    const jsonStr = JSON.stringify(val).replace(/'/g, "''");
    return `'${jsonStr}'`;
  }

  const str = String(val).replace(/'/g, "''");
  return `'${str}'`;
}
