import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { DomainConfig } from '@memberjunction/loom-contracts';

export interface SkywayMigrationOptions {
  outputDir: string;
  version: string;
  description: string;
  domain: DomainConfig;
  data: Record<string, readonly Record<string, unknown>[]>;
  dialect?: 'sqlserver' | 'postgres';
}

/**
 * Emits additive Skyway migrations for generated delta records.
 */
export async function emitSkywayMigration(options: SkywayMigrationOptions): Promise<string> {
  await fs.mkdir(options.outputDir, { recursive: true });

  const safeDesc = options.description.replace(/[^a-zA-Z0-9_]/g, '_');
  const fileName = `V${options.version}__${safeDesc}.sql`;
  const filePath = path.join(options.outputDir, fileName);

  const lines: string[] = [
    `-- =============================================================================`,
    `-- Migration: ${fileName}`,
    `-- Generated by Loom Simulation Engine (MemberJunction)`,
    `-- Target Dialect: ${options.dialect ?? 'sqlserver'}`,
    `-- =============================================================================`,
    ``,
    `BEGIN TRANSACTION;`,
    ``,
  ];

  for (const [entityName, records] of Object.entries(options.data)) {
    if (records.length === 0) continue;
    const entityCfg = options.domain.entities[entityName];
    const table = entityCfg ? `${entityCfg.schema}.${entityCfg.targetTable}` : entityName;

    lines.push(`-- Entity: ${entityName} (${records.length} records)`);

    for (const record of records) {
      const cols = Object.keys(record);
      const vals = cols.map((col) => formatSqlValue(record[col]));
      lines.push(
        `INSERT INTO ${table} (${cols.map((c) => `[${c}]`).join(', ')}) VALUES (${vals.join(', ')});`
      );
    }
    lines.push(``);
  }

  lines.push(`COMMIT TRANSACTION;`);
  lines.push(``);

  await fs.writeFile(filePath, lines.join('\n'), 'utf8');
  return filePath;
}

function formatSqlValue(val: unknown): string {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return String(val);
  if (typeof val === 'boolean') return val ? '1' : '0';
  const str = String(val).replace(/'/g, "''");
  return `'${str}'`;
}
