import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { DomainConfig } from '@memberjunction/loom-contracts';

export interface SkywayMigrationOptions {
  outputDir: string;
  version: string;
  description: string;
  domain: DomainConfig;
  data: Record<string, readonly Record<string, unknown>[]>;
  dialect?: 'sqlserver' | 'postgres';
  useSpCreate?: boolean;
}

/**
 * Emits additive Skyway migrations with dual-dialect support (SQL Server & PostgreSQL).
 * Properly escapes JSON objects and strings, avoiding [object Object] leaks.
 */
export async function emitSkywayMigration(options: SkywayMigrationOptions): Promise<string> {
  await fs.mkdir(options.outputDir, { recursive: true });

  const dialect = options.dialect ?? 'sqlserver';
  const isPostgres = dialect === 'postgres';
  const safeDesc = options.description.replace(/[^a-zA-Z0-9_]/g, '_');
  const fileName = `V${options.version}__${safeDesc}.sql`;
  const filePath = path.join(options.outputDir, fileName);

  const lines: string[] = [
    `-- =============================================================================`,
    `-- Migration: ${fileName}`,
    `-- Generated by Loom Simulation Engine (MemberJunction)`,
    `-- Target Dialect: ${dialect}`,
    `-- =============================================================================`,
    ``,
    isPostgres ? `BEGIN;` : `BEGIN TRANSACTION;`,
    ``,
  ];

  for (const [entityName, records] of Object.entries(options.data)) {
    if (records.length === 0) continue;
    const entityCfg = options.domain.entities[entityName];
    const schemaName = entityCfg?.schema ?? 'dbo';
    const tableName = entityCfg?.targetTable ?? entityName;

    const fullTableName = isPostgres
      ? `"${schemaName}"."${tableName}"`
      : `[${schemaName}].[${tableName}]`;

    lines.push(`-- Entity: ${entityName} (${records.length} records)`);

    for (const record of records) {
      const cols = Object.keys(record);
      const colList = isPostgres
        ? cols.map((c) => `"${c}"`).join(', ')
        : cols.map((c) => `[${c}]`).join(', ');

      const valList = cols
        .map((col) => formatSqlValue(record[col], isPostgres))
        .join(', ');

      if (options.useSpCreate) {
        // Procedure-based insertion: spCreate<EntityName>
        const spName = isPostgres
          ? `"${schemaName}"."spCreate${tableName}"`
          : `[${schemaName}].[spCreate${tableName}]`;
        const paramList = cols
          .map((c) => `@${c} = ${formatSqlValue(record[c], isPostgres)}`)
          .join(', ');
        lines.push(`EXEC ${spName} ${paramList};`);
      } else {
        // Direct transactional SQL insert
        lines.push(`INSERT INTO ${fullTableName} (${colList}) VALUES (${valList});`);
      }
    }
    lines.push(``);
  }

  lines.push(isPostgres ? `COMMIT;` : `COMMIT TRANSACTION;`);
  lines.push(``);

  await fs.writeFile(filePath, lines.join('\n'), 'utf8');
  return filePath;
}

function formatSqlValue(val: unknown, isPostgres: boolean): string {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return String(val);
  if (typeof val === 'boolean') return isPostgres ? (val ? 'TRUE' : 'FALSE') : val ? '1' : '0';

  if (typeof val === 'object') {
    // Serialize nested objects/arrays as JSON, never [object Object]
    const jsonStr = JSON.stringify(val).replace(/'/g, "''");
    return `'${jsonStr}'`;
  }

  const str = String(val).replace(/'/g, "''");
  return `'${str}'`;
}
